### PR TITLE
JBIDE-28494: Can't open application.properties on Windows

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by olkornii** [comment]
Works for me with steps:
Install jbt from https://download.jboss.org/jbosstools/photon/staging/updates/ -> restart -> build quarkus from https://github.com/jeffmaury/jbosstools-quarkus/tree/JBIDE-28494 with "mvn clean verify -DskipTests=True"* and java11** -> install locally built quarkus -> application.properties can be opened

*some tests fails, see screenshot, thats why there is "-DskipTests=True"

image


**java11 because fails if default java is 17, see screenshot

image

**Review by olkornii — CHANGES_REQUESTED** [review]
Check my last comment please

**Comment by jeffmaury** [comment]
> @jeffmaury Check my last comment please

That's an issue with your JDK

**Comment by olkornii** [comment]
@jeffmaury 
Do you want me to do something more or its enough for merge?

**Comment by jeffmaury** [comment]
No I asked you to review it because you were the issue author. Feel free to accept or reject the PR

**Review by olkornii — APPROVED** [review]

**Comment by olkornii** [comment]
Its ok, as for me. Thanks :)

**Pull request merged**
