### PR TITLE
JBIDE-27534: codeLens / codeMining does not work any more

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

@jkopriva @odockal wanted to add a unit test but don't know how to deal with
- double click
- code mining in text editor

### CODE REVIEW

**Comment by jkopriva** [comment]
@olkornii can you please look at this? Thank you!

**Comment by olkornii** [comment]
@jeffmaury codeLens works again. What about "double click", what do you mean ?

**Comment by jeffmaury** [comment]
@olkornii I wanted to write a RedDeer test that could validate codeLens but I missed:

- how to handle double click as I need to generate a Quarkus REST application so I need to explicitly enable extensions
- how to get access to code minings from an editor

**Comment by olkornii** [comment]
@jeffmaury 
   1. if i understood you right, you need this one (as me, for one of my tests): https://issues.redhat.com/browse/JBIDE-27448
   2. @odockal advise that (not exactly, but might help): https://github.com/jbosstools/jbosstools-openshift/blob/master/test-framework/org.jboss.tools.openshift.reddeer/src/org/jboss/tools/openshift/reddeer/utils/EmulatedLinkStyledText.java

**Comment by jeffmaury** [comment]
Yes if wizard does not require any more double click that may fix the issue.
Need also to check if EmulatedStyleLink is relevant for code mining in the editor

**Pull request merged**
