### PR TITLE
JBIDE-27766: Double click on the "Run" button to start, a single is e…

### PR DESCRIPTION
**Pull request by jeffmaury**
…xpected

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jeffmaury** [comment]
@olkornii can you review/test

**Comment by olkornii** [comment]
@jeffmaury same as previously. It looks like first click on "Run" works as "Apply", even if I have no changes. This problem is only in new projects, in previously created has no problems.

**Comment by jeffmaury** [comment]
@olkornii can you retest as I can't reproduce on my WIn10 workstation

**Comment by olkornii** [comment]
@jeffmaury Now it works for me on both machines (RHEL and Windows10)

**Comment by jeffmaury** [comment]
testPR

**Pull request merged**
