### PR TITLE
JBIDE-27573: Support codestart option in project wizard

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jeffmaury** [comment]
testPR

**Review by sbouchet — APPROVED** [review]
LGTM. I needed to figure out how to test since the wizard page is not very intuitive.
I tested with the REST extension and checking the 'example code' checkbox produced the expected source code to be generated.

**Comment by jeffmaury** [comment]
> 
> 
> LGTM. I needed to figure out how to test since the wizard page is not very intuitive.
> I tested with the REST extension and checking the 'example code' checkbox produced the expected source code to be generated.

I was thinking on adding a message on the right of the checkbox to explain what is this option about

**Review by sbouchet — APPROVED** [review]
with added text it's more friendly.

**Pull request merged**
