### PR TITLE
Add support for application.yaml

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

# Pull Request Checklist
## General
* Is this a blocking issue or new feature? If yes, QE needs to +1 this PR

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?

## Testing
* Are there unit-tests?
* Are there integration tests (or at least a jira to tackle these)?
* Is the non-happy path working, too?
* Are other parts that use the same component still working fine?

## Function
* Does it work?

### CODE REVIEW

**Comment by jkopriva** [comment]
@olkornii can you please also review this? Thank you!

**Comment by sbouchet** [comment]
I tested locally by adding aplication.yaml suuport by running :
`./mvnw quarkus:add-extension -Dextensions="config-yaml"` then trying to edit a new application.yaml file along to the default application.properties. seems to work but i need more time to fully review/test. feel free to review on your side .

**Comment by olkornii** [comment]
I did the same as Stephane:
1. I ran ./mvnw quarkus: add-extension -Dextensions = "config-yaml" in the project folder
2. create application.yaml next to application.properties
3. added to .yaml file:
quarkus:
    application:
       name: my_new_test_name
4. it works

**Review by sbouchet — APPROVED** [review]
LGTM.

**Pull request merged**
